# GENERAL
project_name: "bilstm-multitask"
random_seed: 42
test_run: False
test_run_n_samples: 10
device: "cuda:0"
multitask: True
results_dir: "results"

# MODEL
architecture: "BiLSTMMultitask"
dim_emb: 256
dim_hid: 20
num_layers: 2

# TRAINING
start_epoch: 0
max_epochs: 7
logging_freq: 20
early_stopping: True
early_stopping_metric: "f1"
early_stopping_label_col: "scv"
batch_size: 32
shuffle: False
tasks:
- "classification"
- "classification"

# DATA
data_filepath: "data/rule_based_annotations.csv"
num_classes_list:
- 3
- 3
label_cols:
- "apv"
- "scv"
label_criterion:
- "CrossEntropyLoss"
- "CrossEntropyLoss"

# OPTIMIZER
optimizer: "ADAM"
base_lr: 0.001
weight_decay: 0.0001
grad_clip: 5
