# GENERAL
project_name: "bilstm-apv"
random_seed: 42
test_run: False
test_run_n_samples: 10
device: "cuda:0"
multitask: True

# MODEL
architecture: "BiLSTMMultitask"
dim_emb: 256
dim_hid: 20
num_layers: 2

# TRAINING
start_epoch: 0
max_epochs: 5
early_stopping: False
batch_size: 32

# DATA
train_data_filepath: "TODO"
test_data_filepath: "TODO"
num_classes_list:
- 1
- 3
- 3
- 3
label_cols:
- "svo_dist"
- "apv"
- "scv"
- "hv"
label_criterion:
- "MSELoss"
- "CrossEntropyLoss"
- "CrossEntropyLoss"
- "CrossEntropyLoss"

# OPTIMIZER
optimizer: "ADAM"
base_lr: 0.001
weight_decay: 0.0001
grad_clip: 5
