# GENERAL
project_name: "bert-scv"
random_seed: 42
test_run: False
test_run_n_samples: 10
device: "cuda:0"
multitask: False
results_dir: "results"

# MODEL
architecture: "BERTClassifier"
dim_hid: 20
freeze_pretrained: False

# TRAINING
logging_freq: 20
start_epoch: 0
max_epochs: 3
early_stopping: True
early_stopping_metric: "f1"
batch_size: 32
shuffle: False
task: "classification"

# DATA
data_filepath: "data/rule_based_annotations_old_svo_dist.csv"
num_classes: 3
label_col: "scv"
label_description: "simplest form of verb(s)"
label_criterion: "CrossEntropyLoss"

# OPTIMIZER
optimizer: "ADAM"
base_lr: 0.001
weight_decay: 0.0001
grad_clip: 5
