# GENERAL
project_name: "bert-svo_dist_norm"
random_seed: 42
test_run: False
test_run_n_samples: 10
device: "cuda:0"
multitask: False
results_dir: "results"

# MODEL
architecture: "BERTRegressor"
dim_hid: 20
freeze_pretrained: False

# TRAINING
logging_freq: 20
start_epoch: 0
max_epochs: 3
early_stopping: True
early_stopping_metric: "r2"
batch_size: 32
shuffle: False
task: "regression"

# DATA
data_filepath: "data/rule_based_annotations.csv"
label_col: "svo_dist_norm"
label_description: "subject verb object distance"
label_criterion: "MSELoss"

# OPTIMIZER
optimizer: "ADAM"
base_lr: 0.001
weight_decay: 0.0001
grad_clip: 5