# GENERAL
project_name: "bilstm-apv"
random_seed: 42
test_run: False
test_run_n_samples: 10
device: "cuda:0"
multitask: False
results_dir: "results"

# MODEL
architecture: "BiLSTMClassifier"
dim_emb: 256
dim_hid: 20
num_layers: 2

# TRAINING
logging_freq: 20
start_epoch: 0
max_epochs: 40
early_stopping: True
early_stopping_metric: "acc"
batch_size: 32
shuffle: False
task: "classification"

# DATA
data_filepath: "data/rule_based_annotations.csv"
num_classes: 3
label_col: "apv"
label_description: "active/passive voice"
label_criterion: "CrossEntropyLoss"

# OPTIMIZER
optimizer: "ADAM"
base_lr: 0.001
weight_decay: 0.0001
grad_clip: 5
