# GENERAL
project_name: "bilstm-svo_dist_norm"
random_seed: 42
test_run: False
test_run_n_samples: 10
device: "cuda:0"
multitask: False
results_dir: "results"

# MODEL
architecture: "BiLSTMRegressor"
dim_emb: 256
dim_hid: 20
num_layers: 2

# TRAINING
logging_freq: 20
start_epoch: 0
max_epochs: 5
early_stopping: False
batch_size: 32
shuffle: False
task: "regression"

# DATA
data_filepath: "data/rule_based_annotations.csv"
label_col: "svo_dist_norm"
label_description: "subject verb object distance normalized"
label_criterion: "MSELoss"

# OPTIMIZER
optimizer: "ADAM"
base_lr: 0.001
weight_decay: 0.0001
grad_clip: 5